<?php

/**
 * @file
 * Contains view_stats.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function view_stats_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the view_stats module.
    case 'help.page.view_stats':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('View statistics for each node') . '</p>';
      return $output;

    default:
  }
}
