<?php

/**
 * @file
 * Contains taxonomy_rating.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\flag\FlagInterface;

/**
 * Implements hook_help().
 */
function taxonomy_rating_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the taxonomy_rating module.
    case 'help.page.taxonomy_rating':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Taxonomy rating based on connected entities rate points (&#039;likes&#039;)') . '</p>';
      return $output;

    default:
  }
}

/**
 *
 */
function taxonomy_rating_taxonomy_term_view(){
  $term = \Drupal::routeMatch()->getParameter('taxonomy_term');
  if ($term) {
    $tid = $term->id();
  }
  else {
    return;
  }

  \Drupal::service('taxonomy_rating')->calculate($tid);
}

function taxonomy_rating_cron(){
  $config = \Drupal::config('taxonomy_rating.settings');
  $calculation_method = $config->get('calculation_method');
  if($calculation_method=='onCron') {
    $query = \Drupal::entityQuery('taxonomy_term')
      ->condition('vid', 'genres');
    $genre_tids = $query->execute();
    $term_storage = \Drupal::entityManager()->getStorage('taxonomy_term');
    $terms = $term_storage->loadMultiple(array_values($genre_tids));
    foreach ($genre_tids as $genre_tid) {
      $terms[$genre_tid]->field_genre_rating->value = \Drupal::service('taxonomy_rating')
        ->calculate($genre_tid);;
      $terms[$genre_tid]->save();
    }
  }
  else {
    return;
  }
}

