<?php

/**
 * @file
 * Contains nodes_editor.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nodes_editor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nodes_editor module.
    case 'help.page.nodes_editor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a simple nodes edition options') . '</p>';
      return $output;

    default:
  }
}
